version: "3.7"
services:
  goblog:
    build:
      context: .
      target: dev
    container_name: goblog
    command: CompileDaemon --build="go build -o main ./cmd/blog" --command=./main
    environment:
      PG_HOST: ${GOBLOG_HOST}
      PG_DB: ${GOBLOG_DATABASE}
      PG_USER: ${GOBLOG_USER}
      PG_PORT: ${GOBLOG_PORT}
      PG_PASSWORD: ${GOBLOG_PASSWORD}
    volumes:
      - ./src:/src
    networks:
      - pgnet

  db:
    image: postgres:12.5-alpine
    container_name: db
    environment:
      POSTGRES_DB: ${GOBLOG_DATABASE}
      POSTGRES_USER: ${GOBLOG_USER}
      POSTGRES_PASSWORD: ${GOBLOG_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgnet

networks:
  pgnet:
volumes:
  pgdata:
